ALTER TABLE unit
    ADD COLUMN identifier VARCHAR(20) NOT NULL DEFAULT '';

ALTER TABLE call
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN finished_at TIMESTAMP;

ALTER TABLE comment
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();